- hosts: web
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Upgrade packages
    yum:
      name: '*'
      state: latest
  - name: Install Apache
    yum:
      name: httpd
      state: present
    notify:
     - Restart Apache  
  - name: Create Webpage
    shell:
      cmd: echo "Hello from the Ansible configured website" >/var/www/html/index.html
  - name: Copy Files
    copy:
      src: /home/sumit/Documents/Ansible/AWS/mysite/
      dest: /var/www/html/ 
      mode: '777'     
  - name: Get public IP
    shell:
      cmd: ifconfig
    register: ifconfig
  - debug: var=ifconfig.stdout_lines
  handlers  :
  - name: Restart Apache
    service: 
      name: httpd
      state: reloaded