---
# tasks file for web
- name: update packages
  yum:
    name: '*'
    state: latest
- name: install apache
  yum:
    name: httpd
    state: installed
  notify:
    - start apache
- name: Get public ip
  shell:
    cmd: curl http://169.254.169.254/latest/meta-data/public-ipv4
  register: curl
- debug: var=curl.stdout_lines
- name: Create temp webpage
  shell:
    cmd: echo "hello from" + "curl http://169.254.169.254/latest/meta-data/public-ipv4" > /var/www/html/index.html

